name: macos-vnc

on:
  workflow_dispatch:

jobs:
  vnc:
    runs-on: macos-latest
    steps:
      - name: Install Tailscale
        run: |
          brew install tailscale
      - name: Start tailscaled
        run: |
          sudo /opt/homebrew/opt/tailscale/bin/tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &
          sleep 5
      - name: Login Tailscale
        run: |
          sudo /opt/homebrew/bin/tailscale up \
            --authkey=${{ secrets.TAILSCALE_AUTH }} \
            --hostname=gh-macos-runner \
            --accept-routes --accept-dns=false \
            --ssh=false
            
      - name: Setup VNC password
        id: vncpass
        run: |
          # Random password 8 ký tự
          PASS=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 8)
        
           # Enable VNC legacy auth (password-only)
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -clientopts -setvnclegacy -vnclegacy yes \
            -configure -clientopts -setvncpw -vncpw "$PASS"
        
          echo "VNC_PASS=$PASS" >> $GITHUB_ENV
          echo "$PASS" > vnc-password.txt

      - name: Enable VNC server
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -restart -agent -privs -all

      - name: Show connection info
        run: |
          echo "======================================="
          echo "Tailscale IP: $(tailscale ip -4)"
          echo "VNC password saved as artifact."
          echo "Use: vnc://<tailscale-ip>"
          echo "======================================="

      - name: Upload VNC password artifact
        uses: actions/upload-artifact@v4
        with:
          name: vnc-password
          path: vnc-password.txt
          retention-days: 1
